{
 "title": "Checkout",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "paredao", "label": "Paredão", "query": "label_values(paredao)" }
  ]
 },
 "panels": [
  {
   "title": "Total de votos",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "votacao_total{paredao=\"$paredao\"}"
    }
   ]
  },
  {
   "title": "Andamento da votação",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(votacao_total{paredao=\"$paredao\"}[1m])",
     "legendFormat": "Total de votos"
    }
   ]
  },
  {
   "title": "Total por participante",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (participante) (emparedado_total{paredao=\"$paredao\"}))",
     "legendFormat": "{{participante}}"
    }
   ]
  },
  {
   "title": "Evolução por participante",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (participante) (rate(emparedado_total{paredao=\"$paredao\"}[1m]))",
     "legendFormat": "{{participante}}"
    }
   ]
  },
  {
   "title": "Tempo de resposta (95 percentil)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "time in ms"
    }
   ]
  }
 ]
}