global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'tchaki-tchaki'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.24.0.1:8080']